export const SWITCH_CURRENCY = "SWITCH_CURRENCY";
export const TOGGLE_CURRENCY = "TOGGLE_CURRENCY";

export const TOGGLE_MINI_CART = "TOGGLE_MINI_CART";
export const CLOSE_MINI_CART = "CLOSE_MINI_CART";

export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";

export const ADD_TO_CART = "ADD_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";

export const ADD_SELECTED_OPTION = "ADD_SELECTED_OPTION";
export const UPDATE_SELECTED_OPTION = "UPDATE_SELECTED_OPTION";
export const CLEAR_SELECTED_OPTIONS = "CLEAR_SELECTED_OPTIONS";
